import type { Product, Category, Banner, Coupon, Settings, Review, ProductSpec, ConditionReport } from '@/types';

export const isSupabaseConfigured = Boolean(
  import.meta.env.VITE_SUPABASE_URL && import.meta.env.VITE_SUPABASE_ANON_KEY
);

export const mockCategories: Category[] = [
  { id: 'cat-1', name: 'Phones', slug: 'phones', icon: 'Smartphone', image_url: null, description: null, sort_order: 1 },
  { id: 'cat-2', name: 'Laptops', slug: 'laptops', icon: 'Laptop', image_url: null, description: null, sort_order: 2 },
  { id: 'cat-3', name: 'Tablets', slug: 'tablets', icon: 'Tablet', image_url: null, description: null, sort_order: 3 },
  { id: 'cat-4', name: 'Smart Watches', slug: 'smart-watches', icon: 'Watch', image_url: null, description: null, sort_order: 4 },
  { id: 'cat-5', name: 'Air Conditioners', slug: 'air-conditioners', icon: 'Wind', image_url: null, description: null, sort_order: 5 },
  { id: 'cat-6', name: 'TVs', slug: 'tvs', icon: 'Tv', image_url: null, description: null, sort_order: 6 },
  { id: 'cat-7', name: 'Refrigerators', slug: 'refrigerators', icon: 'Refrigerator', image_url: null, description: null, sort_order: 7 },
  { id: 'cat-8', name: 'Washing Machines', slug: 'washing-machines', icon: 'WashingMachine', image_url: null, description: null, sort_order: 8 },
  { id: 'cat-9', name: 'Furniture', slug: 'furniture', icon: 'Sofa', image_url: null, description: null, sort_order: 9 },
  { id: 'cat-10', name: 'Office Equipment', slug: 'office-equipment', icon: 'Printer', image_url: null, description: null, sort_order: 10 },
  { id: 'cat-11', name: 'Gaming Consoles', slug: 'gaming-consoles', icon: 'Gamepad2', image_url: null, description: null, sort_order: 11 },
  { id: 'cat-12', name: 'Cameras', slug: 'cameras', icon: 'Camera', image_url: null, description: null, sort_order: 12 },
  { id: 'cat-13', name: 'Speakers', slug: 'speakers', icon: 'Speaker', image_url: null, description: null, sort_order: 13 },
  { id: 'cat-14', name: 'Home Appliances', slug: 'home-appliances', icon: 'Microwave', image_url: null, description: null, sort_order: 14 },
  { id: 'cat-15', name: 'Electronics', slug: 'electronics', icon: 'CircuitBoard', image_url: null, description: null, sort_order: 15 },
  { id: 'cat-16', name: 'Gadgets', slug: 'gadgets', icon: 'Gadget', image_url: null, description: null, sort_order: 16 },
  { id: 'cat-17', name: 'Cars', slug: 'cars', icon: 'Car', image_url: null, description: null, sort_order: 17 },
  { id: 'cat-18', name: 'Motorcycles', slug: 'motorcycles', icon: 'Bike', image_url: null, description: null, sort_order: 18 },
  { id: 'cat-19', name: 'Accessories', slug: 'accessories', icon: 'Cable', image_url: null, description: null, sort_order: 19 },
];

const img = (id: number) => `https://images.pexels.com/photos/${id}/pexels-photo-${id}.jpeg?auto=compress&cs=tinysrgb&h=650&w=940`;

export const mockProducts: Product[] = [
  {
    id: 'prod-1', name: 'iPhone 16 Pro Max 256GB', slug: 'iphone-16-pro-max-256gb', brand: 'Apple', category_id: 'cat-1',
    short_description: 'Titanium. A18 Pro chip. 48MP Pro camera system.',
    description: 'The iPhone 16 Pro Max features a titanium design, the A18 Pro chip, a Pro-grade 48MP camera system, and USB-C. 6.9-inch Super Retina XDR display with ProMotion and Always-On.',
    price: 2650000, compare_at_price: 2850000, condition: 'Brand New', stock: 25, sku: null, rating: 4.9, review_count: 128, sales_count: 340,
    images: [img(29503887), img(8148581), img(1275228)],
    is_featured: true, is_flash_deal: false, is_new_arrival: true, is_best_seller: true, is_active: true,
    warranty: '1 Year Apple Warranty', delivery_info: 'Free delivery in 2-3 business days',
    created_at: '2026-07-15T10:00:00Z', updated_at: '2026-07-15T10:00:00Z',
  },
  {
    id: 'prod-2', name: 'Samsung Galaxy S24 Ultra', slug: 'samsung-galaxy-s24-ultra', brand: 'Samsung', category_id: 'cat-1',
    short_description: 'AI-powered flagship with 200MP camera.',
    description: 'The Galaxy S24 Ultra features a 6.8-inch QHD+ display, 200MP camera, Snapdragon 8 Gen 3, S Pen, and Galaxy AI features.',
    price: 2150000, compare_at_price: 2350000, condition: 'Brand New', stock: 30, sku: null, rating: 4.8, review_count: 96, sales_count: 210,
    images: [img(10902946), img(11494897)],
    is_featured: true, is_flash_deal: true, is_new_arrival: false, is_best_seller: true, is_active: true,
    warranty: '1 Year Samsung Warranty', delivery_info: 'Free delivery in 2-3 business days',
    created_at: '2026-07-10T10:00:00Z', updated_at: '2026-07-10T10:00:00Z',
  },
  {
    id: 'prod-3', name: 'iPhone 15 Pro 256GB (Pre-owned)', slug: 'iphone-15-pro-256gb-preowned', brand: 'Apple', category_id: 'cat-1',
    short_description: 'Certified pre-owned iPhone 15 Pro, fully inspected.',
    description: 'Professionally inspected iPhone 15 Pro with A17 Pro chip, titanium design, 48MP camera, and Super Retina XDR display. Battery health verified.',
    price: 1450000, compare_at_price: 1750000, condition: 'Excellent', stock: 15, sku: null, rating: 4.7, review_count: 54, sales_count: 180,
    images: [img(30165488), img(6373178)],
    is_featured: false, is_flash_deal: false, is_new_arrival: false, is_best_seller: true, is_active: true,
    warranty: '6 Month BuyAndSellOutlets Warranty', delivery_info: 'Free delivery in 2-3 business days',
    created_at: '2026-06-20T10:00:00Z', updated_at: '2026-06-20T10:00:00Z',
  },
  {
    id: 'prod-4', name: 'Google Pixel 8 Pro', slug: 'google-pixel-8-pro', brand: 'Google', category_id: 'cat-1',
    short_description: 'AI photography powerhouse.',
    description: 'Pixel 8 Pro with 6.7-inch LTPO display, 50MP triple camera, Tensor G3 chip, and 7 years of OS updates.',
    price: 1350000, compare_at_price: 1450000, condition: 'Brand New', stock: 18, sku: null, rating: 4.7, review_count: 72, sales_count: 95,
    images: [img(11494897)],
    is_featured: false, is_flash_deal: true, is_new_arrival: true, is_best_seller: false, is_active: true,
    warranty: '1 Year Google Warranty', delivery_info: 'Free delivery in 2-3 business days',
    created_at: '2026-07-18T10:00:00Z', updated_at: '2026-07-18T10:00:00Z',
  },
  {
    id: 'prod-5', name: 'MacBook Pro 14" M4 Pro', slug: 'macbook-pro-14-m4-pro', brand: 'Apple', category_id: 'cat-2',
    short_description: 'Pro power, supercharged by M4.',
    description: 'MacBook Pro 14-inch with M4 Pro chip, Liquid Retina XDR display, up to 22 hours battery, and pro-grade ports.',
    price: 4250000, compare_at_price: 4500000, condition: 'Brand New', stock: 12, sku: null, rating: 4.9, review_count: 87, sales_count: 150,
    images: [img(2506947), img(8217305)],
    is_featured: true, is_flash_deal: false, is_new_arrival: true, is_best_seller: true, is_active: true,
    warranty: '1 Year Apple Warranty', delivery_info: 'Free delivery in 2-3 business days',
    created_at: '2026-07-12T10:00:00Z', updated_at: '2026-07-12T10:00:00Z',
  },
  {
    id: 'prod-6', name: 'Dell XPS 15', slug: 'dell-xps-15', brand: 'Dell', category_id: 'cat-2',
    short_description: 'Premium 15-inch creator laptop.',
    description: 'Dell XPS 15 with Intel Core i7, NVIDIA RTX 4060, 16GB RAM, 512GB SSD, and a stunning 3.5K OLED display.',
    price: 2850000, compare_at_price: 3100000, condition: 'Brand New', stock: 10, sku: null, rating: 4.6, review_count: 65, sales_count: 88,
    images: [img(5793947), img(34804001)],
    is_featured: false, is_flash_deal: true, is_new_arrival: false, is_best_seller: true, is_active: true,
    warranty: '1 Year Dell Warranty', delivery_info: 'Free delivery in 2-3 business days',
    created_at: '2026-06-28T10:00:00Z', updated_at: '2026-06-28T10:00:00Z',
  },
  {
    id: 'prod-7', name: 'MacBook Air M3 (Pre-owned)', slug: 'macbook-air-m3-preowned', brand: 'Apple', category_id: 'cat-2',
    short_description: 'Certified pre-owned MacBook Air M3.',
    description: 'Professionally inspected MacBook Air with M3 chip, 13.6-inch Liquid Retina display, 8GB RAM, 256GB SSD.',
    price: 1750000, compare_at_price: 2300000, condition: 'Like New', stock: 8, sku: null, rating: 4.8, review_count: 42, sales_count: 120,
    images: [img(5107064), img(986774)],
    is_featured: true, is_flash_deal: false, is_new_arrival: false, is_best_seller: true, is_active: true,
    warranty: '6 Month BuyAndSellOutlets Warranty', delivery_info: 'Free delivery in 2-3 business days',
    created_at: '2026-06-15T10:00:00Z', updated_at: '2026-06-15T10:00:00Z',
  },
  {
    id: 'prod-8', name: 'iPad Pro 12.9" M2', slug: 'ipad-pro-12-9-m2', brand: 'Apple', category_id: 'cat-3',
    short_description: 'The ultimate iPad experience.',
    description: 'iPad Pro 12.9-inch with M2 chip, Liquid Retina XDR display, ProMotion, and Thunderbolt/USB-4.',
    price: 1650000, compare_at_price: 1850000, condition: 'Brand New', stock: 20, sku: null, rating: 4.8, review_count: 76, sales_count: 140,
    images: [img(10535365), img(38639)],
    is_featured: true, is_flash_deal: false, is_new_arrival: true, is_best_seller: true, is_active: true,
    warranty: '1 Year Apple Warranty', delivery_info: 'Free delivery in 2-3 business days',
    created_at: '2026-07-01T10:00:00Z', updated_at: '2026-07-01T10:00:00Z',
  },
  {
    id: 'prod-9', name: 'Apple Watch Ultra 2', slug: 'apple-watch-ultra-2', brand: 'Apple', category_id: 'cat-4',
    short_description: 'The most rugged and capable Apple Watch.',
    description: 'Apple Watch Ultra 2 with S9 SiP, brightest display ever, Double Tap gesture, precision dual-frequency GPS, and advanced health sensors.',
    price: 980000, compare_at_price: 1050000, condition: 'Brand New', stock: 35, sku: null, rating: 4.8, review_count: 92, sales_count: 200,
    images: [img(437038), img(267391)],
    is_featured: true, is_flash_deal: false, is_new_arrival: true, is_best_seller: true, is_active: true,
    warranty: '1 Year Apple Warranty', delivery_info: 'Free delivery in 2-3 business days',
    created_at: '2026-07-05T10:00:00Z', updated_at: '2026-07-05T10:00:00Z',
  },
  {
    id: 'prod-10', name: 'Samsung 55" QLED 4K TV', slug: 'samsung-55-qled-4k-tv', brand: 'Samsung', category_id: 'cat-6',
    short_description: 'Quantum Dot color, 4K clarity.',
    description: 'Samsung 55-inch QLED 4K Smart TV with Quantum HDR, Tizen OS, and ultra-thin design.',
    price: 1750000, compare_at_price: 1950000, condition: 'Brand New', stock: 18, sku: null, rating: 4.7, review_count: 63, sales_count: 120,
    images: [img(5202925)],
    is_featured: true, is_flash_deal: true, is_new_arrival: true, is_best_seller: true, is_active: true,
    warranty: '2 Year Samsung Warranty', delivery_info: 'Free delivery & wall mount',
    created_at: '2026-07-08T10:00:00Z', updated_at: '2026-07-08T10:00:00Z',
  },
  {
    id: 'prod-11', name: 'PlayStation 5 Slim', slug: 'playstation-5-slim', brand: 'Sony', category_id: 'cat-11',
    short_description: 'Next-gen gaming, slimmer design.',
    description: 'PlayStation 5 Slim with 1TB SSD, 4K gaming, DualSense controller, and lightning-fast load times.',
    price: 950000, compare_at_price: 1050000, condition: 'Brand New', stock: 25, sku: null, rating: 4.9, review_count: 156, sales_count: 320,
    images: [img(5626849), img(4714924)],
    is_featured: true, is_flash_deal: true, is_new_arrival: true, is_best_seller: true, is_active: true,
    warranty: '1 Year Sony Warranty', delivery_info: 'Free delivery in 2-3 business days',
    created_at: '2026-07-14T10:00:00Z', updated_at: '2026-07-14T10:00:00Z',
  },
  {
    id: 'prod-12', name: 'Xbox Series X', slug: 'xbox-series-x', brand: 'Microsoft', category_id: 'cat-11',
    short_description: 'The most powerful Xbox ever.',
    description: 'Xbox Series X with 1TB SSD, 4K gaming at 120fps, Quick Resume, and Xbox Game Pass ready.',
    price: 920000, compare_at_price: 1020000, condition: 'Brand New', stock: 20, sku: null, rating: 4.8, review_count: 112, sales_count: 260,
    images: [img(34067678), img(15822010)],
    is_featured: true, is_flash_deal: false, is_new_arrival: true, is_best_seller: true, is_active: true,
    warranty: '1 Year Microsoft Warranty', delivery_info: 'Free delivery in 2-3 business days',
    created_at: '2026-07-03T10:00:00Z', updated_at: '2026-07-03T10:00:00Z',
  },
  {
    id: 'prod-13', name: 'JBL Charge 5', slug: 'jbl-charge-5', brand: 'JBL', category_id: 'cat-13',
    short_description: 'Powerful portable sound, 20-hour battery.',
    description: 'JBL Charge 5 with IP67 waterproof, bold JBL Pro sound, and built-in powerbank function.',
    price: 185000, compare_at_price: 220000, condition: 'Brand New', stock: 40, sku: null, rating: 4.7, review_count: 88, sales_count: 170,
    images: [img(4917455), img(374110)],
    is_featured: true, is_flash_deal: true, is_new_arrival: true, is_best_seller: true, is_active: true,
    warranty: '1 Year JBL Warranty', delivery_info: 'Free delivery in 2-3 business days',
    created_at: '2026-07-16T10:00:00Z', updated_at: '2026-07-16T10:00:00Z',
  },
  {
    id: 'prod-14', name: 'Apple AirPods Pro 2', slug: 'apple-airpods-pro-2', brand: 'Apple', category_id: 'cat-16',
    short_description: 'Adaptive Audio, Active Noise Cancellation.',
    description: 'AirPods Pro 2 with H2 chip, 2x more noise cancellation, Adaptive Audio, and USB-C charging case.',
    price: 420000, compare_at_price: 470000, condition: 'Brand New', stock: 45, sku: null, rating: 4.8, review_count: 134, sales_count: 280,
    images: [img(3921817), img(33797659)],
    is_featured: true, is_flash_deal: false, is_new_arrival: true, is_best_seller: true, is_active: true,
    warranty: '1 Year Apple Warranty', delivery_info: 'Free delivery in 2-3 business days',
    created_at: '2026-07-11T10:00:00Z', updated_at: '2026-07-11T10:00:00Z',
  },
  {
    id: 'prod-15', name: 'Canon EOS R6 Mark II', slug: 'canon-eos-r6-mark-ii', brand: 'Canon', category_id: 'cat-12',
    short_description: 'Pro-grade mirrorless, 24MP full-frame.',
    description: 'Canon EOS R6 Mark II with 24.2MP full-frame sensor, 40fps burst, 4K 60p video, and Dual Pixel AF II.',
    price: 3850000, compare_at_price: 4100000, condition: 'Brand New', stock: 6, sku: null, rating: 4.9, review_count: 38, sales_count: 52,
    images: [img(3989612), img(15111004)],
    is_featured: true, is_flash_deal: false, is_new_arrival: true, is_best_seller: false, is_active: true,
    warranty: '1 Year Canon Warranty', delivery_info: 'Free delivery in 2-3 business days',
    created_at: '2026-07-09T10:00:00Z', updated_at: '2026-07-09T10:00:00Z',
  },
  {
    id: 'prod-16', name: 'LG 2HP Inverter Air Conditioner', slug: 'lg-2hp-inverter-air-conditioner', brand: 'LG', category_id: 'cat-5',
    short_description: 'Energy-efficient cooling with dual inverter.',
    description: 'LG 2HP dual inverter split AC with low noise, fast cooling, and energy savings up to 70%.',
    price: 1250000, compare_at_price: 1450000, condition: 'Brand New', stock: 16, sku: null, rating: 4.7, review_count: 41, sales_count: 75,
    images: [img(32737485), img(34887522)],
    is_featured: true, is_flash_deal: true, is_new_arrival: true, is_best_seller: false, is_active: true,
    warranty: '2 Year LG Warranty', delivery_info: 'Free installation & delivery',
    created_at: '2026-07-06T10:00:00Z', updated_at: '2026-07-06T10:00:00Z',
  },
  {
    id: 'prod-17', name: 'Ergonomic Office Chair', slug: 'ergonomic-office-chair', brand: 'BuyAndSellOutlets Office', category_id: 'cat-10',
    short_description: 'All-day comfort, adjustable support.',
    description: 'Ergonomic mesh office chair with lumbar support, adjustable armrests, and 360-degree swivel.',
    price: 285000, compare_at_price: 350000, condition: 'Brand New', stock: 30, sku: null, rating: 4.5, review_count: 44, sales_count: 88,
    images: [img(8353772), img(9068384)],
    is_featured: true, is_flash_deal: true, is_new_arrival: false, is_best_seller: true, is_active: true,
    warranty: '2 Year Warranty', delivery_info: 'Free delivery in 2-3 business days',
    created_at: '2026-06-25T10:00:00Z', updated_at: '2026-06-25T10:00:00Z',
  },
  {
    id: 'prod-18', name: 'Modern Accent Chair', slug: 'modern-accent-chair', brand: 'BuyAndSellOutlets Home', category_id: 'cat-9',
    short_description: 'Scandinavian-inspired comfort.',
    description: 'Premium accent chair with solid wood frame, high-density foam, and stain-resistant fabric in sage green.',
    price: 385000, compare_at_price: 450000, condition: 'Brand New', stock: 20, sku: null, rating: 4.6, review_count: 28, sales_count: 45,
    images: [img(1647662)],
    is_featured: true, is_flash_deal: false, is_new_arrival: true, is_best_seller: false, is_active: true,
    warranty: '1 Year Warranty', delivery_info: 'Free delivery in 3-5 business days',
    created_at: '2026-07-02T10:00:00Z', updated_at: '2026-07-02T10:00:00Z',
  },
  {
    id: 'prod-19', name: 'Anker Power Bank 20000mAh', slug: 'anker-power-bank-20000mah', brand: 'Anker', category_id: 'cat-15',
    short_description: 'High-capacity charging on the go.',
    description: 'Anker 20000mAh power bank with 30W USB-C PD, PowerIQ 3.0, and 3-device charging.',
    price: 65000, compare_at_price: 85000, condition: 'Brand New', stock: 50, sku: null, rating: 4.7, review_count: 76, sales_count: 130,
    images: [img(4072683)],
    is_featured: false, is_flash_deal: true, is_new_arrival: true, is_best_seller: true, is_active: true,
    warranty: '18 Month Anker Warranty', delivery_info: 'Free delivery in 2-3 business days',
    created_at: '2026-07-17T10:00:00Z', updated_at: '2026-07-17T10:00:00Z',
  },
  {
    id: 'prod-20', name: 'Hisense Double Door Refrigerator', slug: 'hisense-double-door-refrigerator', brand: 'Hisense', category_id: 'cat-7',
    short_description: 'Spacious, smart, and energy efficient.',
    description: 'Hisense double door refrigerator with 350L capacity, inverter compressor, and multi-airflow cooling.',
    price: 1450000, compare_at_price: 1650000, condition: 'Brand New', stock: 7, sku: null, rating: 4.6, review_count: 34, sales_count: 55,
    images: [img(6593607), img(8186517)],
    is_featured: true, is_flash_deal: false, is_new_arrival: true, is_best_seller: false, is_active: true,
    warranty: '2 Year Hisense Warranty', delivery_info: 'Free delivery & setup',
    created_at: '2026-07-04T10:00:00Z', updated_at: '2026-07-04T10:00:00Z',
  },
  {
    id: 'prod-21', name: 'PlayStation 5 (Pre-owned)', slug: 'playstation-5-preowned', brand: 'Sony', category_id: 'cat-11',
    short_description: 'Certified pre-owned PS5, fully tested.',
    description: 'Professionally inspected PlayStation 5 with original controller, cables, and 825GB SSD.',
    price: 680000, compare_at_price: 850000, condition: 'Excellent', stock: 10, sku: null, rating: 4.7, review_count: 68, sales_count: 140,
    images: [img(4714924)],
    is_featured: false, is_flash_deal: true, is_new_arrival: false, is_best_seller: true, is_active: true,
    warranty: '6 Month BuyAndSellOutlets Warranty', delivery_info: 'Free delivery in 2-3 business days',
    created_at: '2026-06-22T10:00:00Z', updated_at: '2026-06-22T10:00:00Z',
  },
  {
    id: 'prod-22', name: 'Sony Alpha A7 IV (Pre-owned)', slug: 'sony-alpha-a7-iv-preowned', brand: 'Sony', category_id: 'cat-12',
    short_description: 'Certified pre-owned full-frame mirrorless.',
    description: 'Professionally inspected Sony A7 IV with 33MP sensor, 4K 60p, and advanced autofocus. Shutter count verified.',
    price: 2850000, compare_at_price: 3800000, condition: 'Like New', stock: 4, sku: null, rating: 4.8, review_count: 25, sales_count: 38,
    images: [img(6891485), img(15111004)],
    is_featured: true, is_flash_deal: false, is_new_arrival: false, is_best_seller: true, is_active: true,
    warranty: '6 Month BuyAndSellOutlets Warranty', delivery_info: 'Free delivery in 2-3 business days',
    created_at: '2026-06-18T10:00:00Z', updated_at: '2026-06-18T10:00:00Z',
  },
  {
    id: 'prod-23', name: 'Ninja Blender 1200W', slug: 'ninja-blender-1200w', brand: 'Ninja', category_id: 'cat-14',
    short_description: 'Crush, blend, and process with power.',
    description: 'Ninja 1200W blender with Auto-iQ programs, 72oz pitcher, and Pro Extractor Blades.',
    price: 145000, compare_at_price: 175000, condition: 'Brand New', stock: 35, sku: null, rating: 4.6, review_count: 58, sales_count: 95,
    images: [img(19599327), img(19599329)],
    is_featured: false, is_flash_deal: true, is_new_arrival: true, is_best_seller: false, is_active: true,
    warranty: '1 Year Ninja Warranty', delivery_info: 'Free delivery in 2-3 business days',
    created_at: '2026-07-13T10:00:00Z', updated_at: '2026-07-13T10:00:00Z',
  },
  {
    id: 'prod-24', name: 'Toyota Corolla (Foreign Used)', slug: 'toyota-corolla-foreign-used', brand: 'Toyota', category_id: 'cat-17',
    short_description: 'Certified foreign-used sedan, full service history.',
    description: 'Professionally inspected Toyota Corolla with low mileage, full service history, and fuel-efficient 1.8L engine.',
    price: 18500000, compare_at_price: 20500000, condition: 'Excellent', stock: 1, sku: null, rating: 4.7, review_count: 12, sales_count: 1,
    images: [img(15264151)],
    is_featured: true, is_flash_deal: false, is_new_arrival: true, is_best_seller: false, is_active: true,
    warranty: '1 Year BuyAndSellOutlets Warranty', delivery_info: 'Nationwide delivery available',
    created_at: '2026-07-07T10:00:00Z', updated_at: '2026-07-07T10:00:00Z',
  },
  {
    id: 'prod-25', name: 'Honda Accord (Foreign Used)', slug: 'honda-accord-foreign-used', brand: 'Honda', category_id: 'cat-17',
    short_description: 'Certified foreign-used sedan, premium comfort.',
    description: 'Professionally inspected Honda Accord with low mileage, full service history, and 2.0L i-VTEC engine.',
    price: 22000000, compare_at_price: 24500000, condition: 'Excellent', stock: 1, sku: null, rating: 4.8, review_count: 9, sales_count: 1,
    images: [img(26551186)],
    is_featured: true, is_flash_deal: false, is_new_arrival: true, is_best_seller: false, is_active: true,
    warranty: '1 Year BuyAndSellOutlets Warranty', delivery_info: 'Nationwide delivery available',
    created_at: '2026-07-19T10:00:00Z', updated_at: '2026-07-19T10:00:00Z',
  },
  {
    id: 'prod-26', name: 'USB-C Fast Charger 65W', slug: 'usb-c-fast-charger-65w', brand: 'Anker', category_id: 'cat-19',
    short_description: 'GaN II technology, compact power.',
    description: 'Anker 65W USB-C charger with GaN II tech, PowerIQ 3.0, and dual-port charging.',
    price: 42000, compare_at_price: 55000, condition: 'Brand New', stock: 80, sku: null, rating: 4.6, review_count: 54, sales_count: 92,
    images: [img(4195332), img(4387770)],
    is_featured: false, is_flash_deal: false, is_new_arrival: true, is_best_seller: true, is_active: true,
    warranty: '18 Month Anker Warranty', delivery_info: 'Free delivery in 2-3 business days',
    created_at: '2026-07-20T10:00:00Z', updated_at: '2026-07-20T10:00:00Z',
  },
  {
    id: 'prod-27', name: 'HP Spectre x360', slug: 'hp-spectre-x360', brand: 'HP', category_id: 'cat-2',
    short_description: '2-in-1 luxury convertible laptop.',
    description: 'HP Spectre x360 with Intel Core Ultra 7, 16GB RAM, 1TB SSD, 14-inch OLED touchscreen, and 360-degree hinge.',
    price: 2150000, compare_at_price: 2400000, condition: 'Brand New', stock: 14, sku: null, rating: 4.7, review_count: 58, sales_count: 72,
    images: [img(459653), img(1024751)],
    is_featured: true, is_flash_deal: false, is_new_arrival: true, is_best_seller: true, is_active: true,
    warranty: '1 Year HP Warranty', delivery_info: 'Free delivery in 2-3 business days',
    created_at: '2026-07-21T10:00:00Z', updated_at: '2026-07-21T10:00:00Z',
  },
];

export const mockBanners: Banner[] = [
  {
    id: 'ban-1', title: 'Certified Pre-Owned. Professionally Inspected.',
    subtitle: 'Every refurbished product is tested, graded, and backed by warranty. Save up to 40% without the risk.',
    image_url: img(13577780), cta_text: 'Shop Pre-Owned', cta_link: '/products?condition=pre-owned',
    sort_order: 1, is_active: true,
  },
  {
    id: 'ban-2', title: 'New Arrivals Are Here.',
    subtitle: 'The latest phones, laptops, and gadgets from the brands you love.',
    image_url: img(9203155), cta_text: 'Explore New Arrivals', cta_link: '/products?sort=newest',
    sort_order: 2, is_active: true,
  },
  {
    id: 'ban-3', title: 'Flash Deals — Up to 30% Off.',
    subtitle: 'Limited-time savings on premium electronics and appliances. While stocks last.',
    image_url: img(29022333), cta_text: 'Shop Flash Deals', cta_link: '/products?filter=flash-deals',
    sort_order: 3, is_active: true,
  },
];

export const mockCoupons: Coupon[] = [
  { id: 'cou-1', code: 'WELCOME10', type: 'percent', value: 10, min_order: 0, max_discount: 200000, usage_limit: 1000, used_count: 0, is_active: true, expires_at: '2026-12-31T23:59:59Z' },
  { id: 'cou-2', code: 'FLASH20', type: 'percent', value: 20, min_order: 500000, max_discount: 500000, usage_limit: 500, used_count: 0, is_active: true, expires_at: '2026-12-31T23:59:59Z' },
  { id: 'cou-3', code: 'SAVE50K', type: 'fixed', value: 50000, min_order: 500000, max_discount: null, usage_limit: 100, used_count: 0, is_active: true, expires_at: '2026-12-31T23:59:59Z' },
];

export const mockSettings: Settings = {
  site_name: 'BuyAndSellOutlets',
  whatsapp_number: '+2348000000000',
  free_shipping_threshold: '50000',
  flat_shipping_rate: '2500',
  currency: 'NGN',
  currency_symbol: '₦',
  contact_email: 'support@buyandselloutlets.com',
  contact_phone: '+234 800 000 0000',
  address: '12 Adeola Odeon Street, Victoria Island, Lagos, Nigeria',
};

export const mockReviews: Review[] = [
  { id: 'rev-1', product_id: 'prod-3', user_id: 'demo', author_name: 'Adaeze O.', rating: 5, title: 'Absolutely worth it!', comment: 'The condition was exactly as described. Looks and feels brand new. Battery health was 93% as stated. Very happy with my purchase.', is_approved: true, created_at: '2026-07-01T10:00:00Z' },
  { id: 'rev-2', product_id: 'prod-7', user_id: 'demo', author_name: 'Tunde A.', rating: 5, title: 'Excellent service', comment: 'Fast delivery and the laptop arrived in amazing condition. The inspection report gave me confidence. Will buy again.', is_approved: true, created_at: '2026-07-02T10:00:00Z' },
  { id: 'rev-3', product_id: 'prod-21', user_id: 'demo', author_name: 'Chioma N.', rating: 4, title: 'Great console', comment: 'PS5 works perfectly. Came with all accessories as listed. Only wish the box was in better shape but the console itself is flawless.', is_approved: true, created_at: '2026-07-03T10:00:00Z' },
  { id: 'rev-4', product_id: 'prod-10', user_id: 'demo', author_name: 'Emeka O.', rating: 5, title: 'Best purchase this year', comment: 'The QLED TV is stunning. Colors are vibrant and setup was easy. Delivery was faster than expected.', is_approved: true, created_at: '2026-07-04T10:00:00Z' },
  { id: 'rev-5', product_id: 'prod-13', user_id: 'demo', author_name: 'Funke B.', rating: 5, title: 'Sound is incredible', comment: 'JBL Charge 5 fills my entire living room with rich sound. Battery lasts forever. Highly recommend.', is_approved: true, created_at: '2026-07-05T10:00:00Z' },
  { id: 'rev-6', product_id: 'prod-17', user_id: 'demo', author_name: 'David K.', rating: 5, title: 'Perfect for my home office', comment: 'The ergonomic chair is comfortable for long work hours. Assembly was straightforward. Great value.', is_approved: true, created_at: '2026-07-06T10:00:00Z' },
];

export const mockSpecs: Record<string, ProductSpec[]> = {
  'iphone-16-pro-max-256gb': [
    { id: 's1', product_id: 'prod-1', spec_key: 'Display', spec_value: '6.7" Super Retina XDR OLED', sort_order: 1 },
    { id: 's2', product_id: 'prod-1', spec_key: 'Chip', spec_value: 'A17 Pro', sort_order: 2 },
    { id: 's3', product_id: 'prod-1', spec_key: 'Storage', spec_value: '256GB', sort_order: 3 },
    { id: 's4', product_id: 'prod-1', spec_key: 'Camera', spec_value: '48MP Main + 12MP Ultra Wide + 12MP Telephoto', sort_order: 4 },
    { id: 's5', product_id: 'prod-1', spec_key: 'Battery', spec_value: 'Up to 29 hours video playback', sort_order: 5 },
    { id: 's6', product_id: 'prod-1', spec_key: 'Connectivity', spec_value: '5G, Wi-Fi 6E, Bluetooth 5.3, USB-C', sort_order: 6 },
  ],
  'macbook-pro-14-m4-pro': [
    { id: 's7', product_id: 'prod-5', spec_key: 'Display', spec_value: '14.2" Liquid Retina XDR', sort_order: 1 },
    { id: 's8', product_id: 'prod-5', spec_key: 'Chip', spec_value: 'M3 Pro', sort_order: 2 },
    { id: 's9', product_id: 'prod-5', spec_key: 'Memory', spec_value: '18GB unified', sort_order: 3 },
    { id: 's10', product_id: 'prod-5', spec_key: 'Storage', spec_value: '512GB SSD', sort_order: 4 },
    { id: 's11', product_id: 'prod-5', spec_key: 'Battery', spec_value: 'Up to 18 hours', sort_order: 5 },
  ],
  'samsung-55-qled-4k-tv': [
    { id: 's12', product_id: 'prod-10', spec_key: 'Display', spec_value: '55" QLED 4K UHD', sort_order: 1 },
    { id: 's13', product_id: 'prod-10', spec_key: 'Resolution', spec_value: '3840 x 2160', sort_order: 2 },
    { id: 's14', product_id: 'prod-10', spec_key: 'HDR', spec_value: 'Quantum HDR+', sort_order: 3 },
    { id: 's15', product_id: 'prod-10', spec_key: 'Smart OS', spec_value: 'Tizen', sort_order: 4 },
  ],
  'playstation-5-slim': [
    { id: 's16', product_id: 'prod-11', spec_key: 'CPU', spec_value: 'AMD Zen 2, 8 cores', sort_order: 1 },
    { id: 's17', product_id: 'prod-11', spec_key: 'GPU', spec_value: 'AMD RDNA 2, 10.28 TFLOPs', sort_order: 2 },
    { id: 's18', product_id: 'prod-11', spec_key: 'Storage', spec_value: '1TB SSD', sort_order: 3 },
    { id: 's19', product_id: 'prod-11', spec_key: 'Resolution', spec_value: 'Up to 4K 120fps', sort_order: 4 },
  ],
};

export const mockConditionReports: Record<string, ConditionReport> = {
  'iphone-15-pro-256gb-preowned': {
    id: 'cr1', product_id: 'prod-3',
    battery_health: '94% battery health',
    cosmetic_condition: 'Minor scratches on the titanium frame, screen is pristine',
    inspection_report: 'Full diagnostic passed: battery, camera, display, speakers, charging port, Face ID, and water-resistance seals all verified. No repair history.',
    accessories_included: ['Original box', 'USB-C cable', 'Documentation'],
    warranty_period: '6 months',
  },
  'macbook-air-m3-preowned': {
    id: 'cr2', product_id: 'prod-7',
    battery_health: '97% battery health',
    cosmetic_condition: 'No visible scratches or dents, like-new condition',
    inspection_report: 'Full diagnostic passed: battery, keyboard, trackpad, display, ports, Wi-Fi, and Bluetooth all verified. Cycle count: 38.',
    accessories_included: ['Original box', '35W USB-C power adapter', 'USB-C cable'],
    warranty_period: '6 months',
  },
  'playstation-5-preowned': {
    id: 'cr3', product_id: 'prod-21',
    battery_health: 'N/A',
    cosmetic_condition: 'Minor cosmetic wear on chassis, all ports functional',
    inspection_report: 'Full diagnostic: disc drive, HDMI, controllers, cooling fan, and all ports tested. Firmware updated.',
    accessories_included: ['One DualSense controller', 'HDMI cable', 'Power cable'],
    warranty_period: '6 months',
  },
  'sony-alpha-a7-iv-preowned': {
    id: 'cr4', product_id: 'prod-22',
    battery_health: 'N/A',
    cosmetic_condition: 'Body like-new, no scratches on sensor',
    inspection_report: 'Full diagnostic: sensor, shutter (count: 8,400), autofocus, IBIS, and all ports tested. Firmware updated.',
    accessories_included: ['Original box', 'Battery', 'Charger', 'Strap'],
    warranty_period: '6 months',
  },
};
