/*
# Declutter — Seed data (no reviews)

Populates categories (all 20), product catalog (~40 products), condition reports,
product specs, banners, coupons, and default settings.
Uses ON CONFLICT to skip existing rows — safe to re-run.
*/

INSERT INTO public.categories (name, slug, icon, sort_order) VALUES
('Phones','phones','Smartphone',1),
('Laptops','laptops','Laptop',2),
('Tablets','tablets','Tablet',3),
('Smart Watches','smart-watches','Watch',4),
('Air Conditioners','air-conditioners','Wind',5),
('TVs','tvs','Tv',6),
('Refrigerators','refrigerators','Refrigerator',7),
('Washing Machines','washing-machines','WashingMachine',8),
('Furniture','furniture','Sofa',9),
('Office Equipment','office-equipment','Printer',10),
('Gaming Consoles','gaming-consoles','Gamepad2',11),
('Cameras','cameras','Camera',12),
('Speakers','speakers','Speaker',13),
('Home Appliances','home-appliances','Microwave',14),
('Electronics','electronics','CircuitBoard',15),
('Gadgets','gadgets','Gadget',16),
('Cars','cars','Car',17),
('Motorcycles','motorcycles','Bike',18),
('Accessories','accessories','Cable',19)
ON CONFLICT (slug) DO NOTHING;

WITH cat AS (SELECT slug, id FROM public.categories)
INSERT INTO public.products
(name, slug, brand, category_id, short_description, description, price, compare_at_price, condition, stock, rating, review_count, sales_count, images, is_featured, is_flash_deal, is_new_arrival, is_best_seller, warranty, delivery_info)
SELECT * FROM (VALUES
('iPhone 15 Pro Max 256GB','iphone-15-pro-max-256gb','Apple',(SELECT id FROM cat WHERE slug='phones'),'Titanium. Pro camera. A17 Pro chip.','The iPhone 15 Pro Max features a titanium design, the A17 Pro chip, a Pro-grade camera system, and USB-C. 6.7-inch Super Retina XDR display with ProMotion and Always-On.',1599.00,1799.00,'Brand New',25,4.9,128,340,ARRAY['https://images.pexels.com/photos/29503887/pexels-photo-29503887.jpeg?auto=compress&cs=tinysrgb&h=650&w=940','https://images.pexels.com/photos/8148581/pexels-photo-8148581.jpeg?auto=compress&cs=tinysrgb&h=650&w=940','https://images.pexels.com/photos/1275228/pexels-photo-1275228.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'],true,false,true,true,'1 Year Apple Warranty','Free delivery in 2-3 business days'),
('Samsung Galaxy S24 Ultra','samsung-galaxy-s24-ultra','Samsung',(SELECT id FROM cat WHERE slug='phones'),'AI-powered flagship with 200MP camera.','The Galaxy S24 Ultra features a 6.8-inch QHD+ display, 200MP camera, Snapdragon 8 Gen 3, S Pen, and Galaxy AI features.',1299.00,1499.00,'Brand New',30,4.8,96,210,ARRAY['https://images.pexels.com/photos/10902946/pexels-photo-10902946.jpeg?auto=compress&cs=tinysrgb&h=650&w=940','https://images.pexels.com/photos/11494897/pexels-photo-11494897.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'],true,true,false,true,'1 Year Samsung Warranty','Free delivery in 2-3 business days'),
('iPhone 13 128GB (Pre-owned)','iphone-13-128gb-preowned','Apple',(SELECT id FROM cat WHERE slug='phones'),'Certified pre-owned iPhone 13, fully inspected.','Professionally inspected iPhone 13 with A15 Bionic chip, dual 12MP cameras, and Super Retina XDR display. Battery health verified.',649.00,799.00,'Excellent',15,4.7,54,180,ARRAY['https://images.pexels.com/photos/30165488/pexels-photo-30165488.jpeg?auto=compress&cs=tinysrgb&h=650&w=940','https://images.pexels.com/photos/6373178/pexels-photo-6373178.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'],false,false,false,true,'6 Month Declutter Warranty','Free delivery in 2-3 business days'),
('Google Pixel 8 Pro','google-pixel-8-pro','Google',(SELECT id FROM cat WHERE slug='phones'),'AI photography powerhouse.','Pixel 8 Pro with 6.7-inch LTPO display, 50MP triple camera, Tensor G3 chip, and 7 years of OS updates.',999.00,1099.00,'Brand New',18,4.7,72,95,ARRAY['https://images.pexels.com/photos/11494897/pexels-photo-11494897.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'],false,true,true,false,'1 Year Google Warranty','Free delivery in 2-3 business days'),
('MacBook Pro 14" M3 Pro','macbook-pro-14-m3-pro','Apple',(SELECT id FROM cat WHERE slug='laptops'),'Pro power, supercharged by M3.','MacBook Pro 14-inch with M3 Pro chip, Liquid Retina XDR display, up to 18 hours battery, and pro-grade ports.',1999.00,2199.00,'Brand New',12,4.9,87,150,ARRAY['https://images.pexels.com/photos/2506947/pexels-photo-2506947.jpeg?auto=compress&cs=tinysrgb&h=650&w=940','https://images.pexels.com/photos/8217305/pexels-photo-8217305.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'],true,false,true,true,'1 Year Apple Warranty','Free delivery in 2-3 business days'),
('Dell XPS 15','dell-xps-15','Dell',(SELECT id FROM cat WHERE slug='laptops'),'Premium 15-inch creator laptop.','Dell XPS 15 with Intel Core i7, NVIDIA RTX 4060, 16GB RAM, 512GB SSD, and a stunning 3.5K OLED display.',1499.00,1699.00,'Brand New',10,4.6,65,88,ARRAY['https://images.pexels.com/photos/5793947/pexels-photo-5793947.jpeg?auto=compress&cs=tinysrgb&h=650&w=940','https://images.pexels.com/photos/34804001/pexels-photo-34804001.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'],false,true,false,true,'1 Year Dell Warranty','Free delivery in 2-3 business days'),
('MacBook Air M2 (Pre-owned)','macbook-air-m2-preowned','Apple',(SELECT id FROM cat WHERE slug='laptops'),'Certified pre-owned MacBook Air M2.','Professionally inspected MacBook Air with M2 chip, 13.6-inch Liquid Retina display, 8GB RAM, 256GB SSD.',899.00,1199.00,'Like New',8,4.8,42,120,ARRAY['https://images.pexels.com/photos/5107064/pexels-photo-5107064.jpeg?auto=compress&cs=tinysrgb&h=650&w=940','https://images.pexels.com/photos/986774/pexels-photo-986774.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'],true,false,false,true,'6 Month Declutter Warranty','Free delivery in 2-3 business days'),
('HP Spectre x360','hp-spectre-x360','HP',(SELECT id FROM cat WHERE slug='laptops'),'2-in-1 convertible laptop.','HP Spectre x360 with Intel Core i7, 16GB RAM, 1TB SSD, 13.5-inch OLED touchscreen, and gem-cut design.',1249.00,1399.00,'Brand New',14,4.5,38,60,ARRAY['https://images.pexels.com/photos/5082979/pexels-photo-5082979.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'],false,false,true,false,'1 Year HP Warranty','Free delivery in 2-3 business days'),
('iPad Pro 12.9" M2','ipad-pro-12-9-m2','Apple',(SELECT id FROM cat WHERE slug='tablets'),'The ultimate iPad experience.','iPad Pro 12.9-inch with M2 chip, Liquid Retina XDR display, ProMotion, and Thunderbolt/USB-4.',1099.00,1299.00,'Brand New',20,4.8,76,140,ARRAY['https://images.pexels.com/photos/10535365/pexels-photo-10535365.jpeg?auto=compress&cs=tinysrgb&h=650&w=940','https://images.pexels.com/photos/38639/mockup-psd-ipad-iphone-38639.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'],true,false,true,true,'1 Year Apple Warranty','Free delivery in 2-3 business days'),
('Samsung Galaxy Tab S9','samsung-galaxy-tab-s9','Samsung',(SELECT id FROM cat WHERE slug='tablets'),'Premium Android tablet with S Pen.','Galaxy Tab S9 with 11-inch AMOLED display, Snapdragon 8 Gen 2, S Pen included, and IP68 water resistance.',799.00,899.00,'Brand New',22,4.7,51,85,ARRAY['https://images.pexels.com/photos/6373018/pexels-photo-6373018.jpeg?auto=compress&cs=tinysrgb&h=650&w=940','https://images.pexels.com/photos/341523/pexels-photo-341523.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'],false,true,true,false,'1 Year Samsung Warranty','Free delivery in 2-3 business days'),
('iPad Air (Pre-owned)','ipad-air-preowned','Apple',(SELECT id FROM cat WHERE slug='tablets'),'Certified pre-owned iPad Air.','Professionally inspected iPad Air with A14 Bionic chip, 10.9-inch Liquid Retina display, 64GB storage.',499.00,599.00,'Very Good',10,4.6,33,70,ARRAY['https://images.pexels.com/photos/341523/pexels-photo-341523.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'],false,false,false,true,'6 Month Declutter Warranty','Free delivery in 2-3 business days'),
('Apple Watch Series 9','apple-watch-series-9','Apple',(SELECT id FROM cat WHERE slug='smart-watches'),'Smarter. Brighter. More powerful.','Apple Watch Series 9 with S9 SiP, brighter display, Double Tap gesture, and advanced health sensors.',399.00,429.00,'Brand New',35,4.8,92,200,ARRAY['https://images.pexels.com/photos/437038/pexels-photo-437038.jpeg?auto=compress&cs=tinysrgb&h=650&w=940','https://images.pexels.com/photos/267391/pexels-photo-267391.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'],true,false,true,true,'1 Year Apple Warranty','Free delivery in 2-3 business days'),
('Samsung Galaxy Watch 6','samsung-galaxy-watch-6','Samsung',(SELECT id FROM cat WHERE slug='smart-watches'),'Advanced health tracking on your wrist.','Galaxy Watch 6 with improved BioActive sensor, larger display, and personalized sleep coaching.',299.00,349.00,'Brand New',28,4.6,48,110,ARRAY['https://images.pexels.com/photos/51011/pexels-photo-51011.jpeg?auto=compress&cs=tinysrgb&h=650&w=940','https://images.pexels.com/photos/31406895/pexels-photo-31406895.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'],false,true,false,true,'1 Year Samsung Warranty','Free delivery in 2-3 business days'),
('Apple Watch SE (Pre-owned)','apple-watch-se-preowned','Apple',(SELECT id FROM cat WHERE slug='smart-watches'),'Certified pre-owned Apple Watch SE.','Professionally inspected Apple Watch SE with heart rate sensor, fall detection, and retina display.',189.00,249.00,'Excellent',12,4.5,29,65,ARRAY['https://images.pexels.com/photos/437037/pexels-photo-437037.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'],false,false,false,false,'3 Month Declutter Warranty','Free delivery in 2-3 business days'),
('LG Dual Inverter AC 1.5HP','lg-dual-inverter-ac-15hp','LG',(SELECT id FROM cat WHERE slug='air-conditioners'),'Energy-efficient cooling with dual inverter.','LG 1.5HP dual inverter split AC with low noise, fast cooling, and energy savings up to 70%.',799.00,999.00,'Brand New',16,4.7,41,75,ARRAY['https://images.pexels.com/photos/32737485/pexels-photo-32737485.jpeg?auto=compress&cs=tinysrgb&h=650&w=940','https://images.pexels.com/photos/34887522/pexels-photo-34887522.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'],true,true,true,false,'2 Year LG Warranty','Free installation & delivery'),
('Hisense 1HP Split AC (Pre-owned)','hisense-1hp-split-ac-preowned','Hisense',(SELECT id FROM cat WHERE slug='air-conditioners'),'Certified pre-owned split AC, serviced and tested.','Professionally inspected Hisense 1HP split AC with refrigerant topped up and full service.',349.00,549.00,'Good',6,4.3,18,40,ARRAY['https://images.pexels.com/photos/34887522/pexels-photo-34887522.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'],false,false,false,false,'3 Month Declutter Warranty','Free delivery, installation extra'),
('Samsung 55" QLED 4K TV','samsung-55-qled-4k-tv','Samsung',(SELECT id FROM cat WHERE slug='tvs'),'Quantum Dot color, 4K clarity.','Samsung 55-inch QLED 4K Smart TV with Quantum HDR, Tizen OS, and ultra-thin design.',749.00,899.00,'Brand New',18,4.7,63,120,ARRAY['https://images.pexels.com/photos/5202925/pexels-photo-5202925.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'],true,true,true,true,'2 Year Samsung Warranty','Free delivery & wall mount'),
('LG 65" OLED C3','lg-65-oled-c3','LG',(SELECT id FROM cat WHERE slug='tvs'),'Self-lit OLED, infinite contrast.','LG 65-inch OLED evo C3 with a9 AI Processor Gen6, Dolby Vision, and webOS.',1499.00,1799.00,'Brand New',8,4.9,52,90,ARRAY['https://images.pexels.com/photos/5202925/pexels-photo-5202925.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'],true,false,true,true,'2 Year LG Warranty','Free delivery & wall mount'),
('Samsung 4-Door French Door Fridge','samsung-4-door-french-door-fridge','Samsung',(SELECT id FROM cat WHERE slug='refrigerators'),'Spacious, smart, and energy efficient.','Samsung 4-door French Door refrigerator with 28 cu ft capacity, FlexZone drawer, and Family Hub.',1899.00,2199.00,'Brand New',7,4.6,34,55,ARRAY['https://images.pexels.com/photos/6593607/pexels-photo-6593607.jpeg?auto=compress&cs=tinysrgb&h=650&w=940','https://images.pexels.com/photos/8186517/pexels-photo-8186517.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'],true,false,true,false,'2 Year Samsung Warranty','Free delivery & setup'),
('LG Top Freezer Refrigerator (Pre-owned)','lg-top-freezer-fridge-preowned','LG',(SELECT id FROM cat WHERE slug='refrigerators'),'Certified pre-owned refrigerator, cleaned and tested.','Professionally inspected LG 18 cu ft top freezer refrigerator with energy-efficient compressor.',599.00,899.00,'Very Good',5,4.4,22,38,ARRAY['https://images.pexels.com/photos/8186517/pexels-photo-8186517.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'],false,false,false,false,'3 Month Declutter Warranty','Free delivery'),
('LG Front Load Washer 9kg','lg-front-load-washer-9kg','LG',(SELECT id FROM cat WHERE slug='washing-machines'),'AI Direct Drive for smarter washing.','LG 9kg front load washing machine with AI DD, TurboWash, and Steam+ for allergen care.',699.00,849.00,'Brand New',12,4.7,39,72,ARRAY['https://images.pexels.com/photos/4700400/pexels-photo-4700400.jpeg?auto=compress&cs=tinysrgb&h=650&w=940','https://images.pexels.com/photos/34397245/pexels-photo-34397245.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'],true,false,true,false,'2 Year LG Warranty','Free delivery & installation'),
('Samsung Top Load Washer 12kg (Pre-owned)','samsung-top-load-washer-12kg-preowned','Samsung',(SELECT id FROM cat WHERE slug='washing-machines'),'Certified pre-owned top load washer.','Professionally inspected Samsung 12kg top load washer with Eco Bubble and Digital Inverter.',399.00,599.00,'Good',4,4.2,16,30,ARRAY['https://images.pexels.com/photos/34397245/pexels-photo-34397245.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'],false,false,false,false,'3 Month Declutter Warranty','Free delivery'),
('Modern Accent Chair','modern-accent-chair','Declutter Home',(SELECT id FROM cat WHERE slug='furniture'),'Scandinavian-inspired comfort.','Premium accent chair with solid wood frame, high-density foam, and stain-resistant fabric in sage green.',349.00,449.00,'Brand New',20,4.6,28,45,ARRAY['https://images.pexels.com/photos/1647662/pexels-photo-1647662.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'],true,false,true,false,'1 Year Warranty','Free delivery in 3-5 business days'),
('Minimalist 3-Seater Sofa','minimalist-3-seater-sofa','Declutter Home',(SELECT id FROM cat WHERE slug='furniture'),'Clean lines, cloud comfort.','3-seater sofa with premium linen upholstery, solid wood frame, and pocket-sprung cushions.',899.00,1099.00,'Brand New',8,4.7,19,28,ARRAY['https://images.pexels.com/photos/12277215/pexels-photo-12277215.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'],false,false,true,false,'1 Year Warranty','Free delivery in 3-5 business days'),
('Ergonomic Office Chair','ergonomic-office-chair','Declutter Office',(SELECT id FROM cat WHERE slug='office-equipment'),'All-day comfort, adjustable support.','Ergonomic mesh office chair with lumbar support, adjustable armrests, and 360-degree swivel.',249.00,329.00,'Brand New',30,4.5,44,88,ARRAY['https://images.pexels.com/photos/8353772/pexels-photo-8353772.jpeg?auto=compress&cs=tinysrgb&h=650&w=940','https://images.pexels.com/photos/9068384/pexels-photo-9068384.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'],true,true,false,true,'2 Year Warranty','Free delivery in 2-3 business days'),
('Standing Desk Electric','standing-desk-electric','Declutter Office',(SELECT id FROM cat WHERE slug='office-equipment'),'Sit-stand electric desk with memory presets.','Electric height-adjustable standing desk with dual motor, 4 memory presets, and bamboo top.',449.00,599.00,'Brand New',15,4.6,26,42,ARRAY['https://images.pexels.com/photos/9068384/pexels-photo-9068384.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'],false,false,true,false,'2 Year Warranty','Free delivery in 2-3 business days'),
('PlayStation 5 Slim','playstation-5-slim','Sony',(SELECT id FROM cat WHERE slug='gaming-consoles'),'Next-gen gaming, slimmer design.','PlayStation 5 Slim with 1TB SSD, 4K gaming, DualSense controller, and lightning-fast load times.',499.00,549.00,'Brand New',25,4.9,156,320,ARRAY['https://images.pexels.com/photos/5626849/pexels-photo-5626849.jpeg?auto=compress&cs=tinysrgb&h=650&w=940','https://images.pexels.com/photos/4714924/pexels-photo-4714924.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'],true,true,true,true,'1 Year Sony Warranty','Free delivery in 2-3 business days'),
('Xbox Series X','xbox-series-x','Microsoft',(SELECT id FROM cat WHERE slug='gaming-consoles'),'The most powerful Xbox ever.','Xbox Series X with 1TB SSD, 4K gaming at 120fps, Quick Resume, and Xbox Game Pass ready.',499.00,549.00,'Brand New',20,4.8,112,260,ARRAY['https://images.pexels.com/photos/34067678/pexels-photo-34067678.jpeg?auto=compress&cs=tinysrgb&h=650&w=940','https://images.pexels.com/photos/15822010/pexels-photo-15822010.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'],true,false,true,true,'1 Year Microsoft Warranty','Free delivery in 2-3 business days'),
('PlayStation 5 (Pre-owned)','playstation-5-preowned','Sony',(SELECT id FROM cat WHERE slug='gaming-consoles'),'Certified pre-owned PS5, fully tested.','Professionally inspected PlayStation 5 with original controller, cables, and 1TB SSD.',399.00,499.00,'Excellent',10,4.7,68,140,ARRAY['https://images.pexels.com/photos/4714924/pexels-photo-4714924.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'],false,true,false,true,'6 Month Declutter Warranty','Free delivery in 2-3 business days'),
('Canon EOS R6 Mark II','canon-eos-r6-mark-ii','Canon',(SELECT id FROM cat WHERE slug='cameras'),'Pro-grade mirrorless, 24MP full-frame.','Canon EOS R6 Mark II with 24.2MP full-frame sensor, 40fps burst, 4K 60p video, and Dual Pixel AF II.',2499.00,2799.00,'Brand New',6,4.9,38,52,ARRAY['https://images.pexels.com/photos/3989612/pexels-photo-3989612.jpeg?auto=compress&cs=tinysrgb&h=650&w=940','https://images.pexels.com/photos/15111004/pexels-photo-15111004.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'],true,false,true,false,'1 Year Canon Warranty','Free delivery in 2-3 business days'),
('Sony Alpha A7 IV (Pre-owned)','sony-alpha-a7-iv-preowned','Sony',(SELECT id FROM cat WHERE slug='cameras'),'Certified pre-owned full-frame mirrorless.','Professionally inspected Sony A7 IV with 33MP sensor, 4K 60p, and advanced autofocus. Shutter count verified.',1799.00,2499.00,'Like New',4,4.8,25,38,ARRAY['https://images.pexels.com/photos/6891485/pexels-photo-6891485.jpeg?auto=compress&cs=tinysrgb&h=650&w=940','https://images.pexels.com/photos/15111004/pexels-photo-15111004.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'],true,false,false,true,'6 Month Declutter Warranty','Free delivery in 2-3 business days'),
('JBL Charge 5','jbl-charge-5','JBL',(SELECT id FROM cat WHERE slug='speakers'),'Powerful portable sound, 20-hour battery.','JBL Charge 5 with IP67 waterproof, bold JBL Pro sound, and built-in powerbank function.',179.00,199.00,'Brand New',40,4.7,88,170,ARRAY['https://images.pexels.com/photos/4917455/pexels-photo-4917455.jpeg?auto=compress&cs=tinysrgb&h=650&w=940','https://images.pexels.com/photos/374110/pexels-photo-374110.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'],true,true,true,true,'1 Year JBL Warranty','Free delivery in 2-3 business days'),
('Marshall Stanmore III','marshall-stanmore-iii','Marshall',(SELECT id FROM cat WHERE slug='speakers'),'Iconic design, room-filling sound.','Marshall Stanmore III Bluetooth speaker with 80W output, classic design, and dynamic loudness.',299.00,349.00,'Brand New',18,4.8,52,85,ARRAY['https://images.pexels.com/photos/27682103/pexels-photo-27682103.jpeg?auto=compress&cs=tinysrgb&h=650&w=940','https://images.pexels.com/photos/19652337/pexels-photo-19652337.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'],false,false,true,false,'1 Year Marshall Warranty','Free delivery in 2-3 business days'),
('Sonos One (Pre-owned)','sonos-one-preowned','Sonos',(SELECT id FROM cat WHERE slug='speakers'),'Certified pre-owned smart speaker.','Professionally inspected Sonos One with Wi-Fi streaming, voice control, and multi-room audio.',149.00,219.00,'Very Good',10,4.5,31,48,ARRAY['https://images.pexels.com/photos/19652337/pexels-photo-19652337.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'],false,false,false,false,'3 Month Declutter Warranty','Free delivery in 2-3 business days'),
('Ninja Blender 1200W','ninja-blender-1200w','Ninja',(SELECT id FROM cat WHERE slug='home-appliances'),'Crush, blend, and process with power.','Ninja 1200W blender with Auto-iQ programs, 72oz pitcher, and Pro Extractor Blades.',129.00,159.00,'Brand New',35,4.6,58,95,ARRAY['https://images.pexels.com/photos/19599327/pexels-photo-19599327.jpeg?auto=compress&cs=tinysrgb&h=650&w=940','https://images.pexels.com/photos/19599329/pexels-photo-19599329.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'],false,true,true,false,'1 Year Ninja Warranty','Free delivery in 2-3 business days'),
('Vitamix A3500 (Pre-owned)','vitamix-a3500-preowned','Vitamix',(SELECT id FROM cat WHERE slug='home-appliances'),'Certified pre-owned high-performance blender.','Professionally inspected Vitamix A3500 with 2.2HP motor, wireless connectivity, and 5 program settings.',399.00,599.00,'Excellent',6,4.8,22,35,ARRAY['https://images.pexels.com/photos/19599329/pexels-photo-19599329.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'],false,false,false,true,'6 Month Declutter Warranty','Free delivery in 2-3 business days'),
('Anker Power Bank 20000mAh','anker-power-bank-20000mah','Anker',(SELECT id FROM cat WHERE slug='electronics'),'High-capacity charging on the go.','Anker 20000mAh power bank with 30W USB-C PD, PowerIQ 3.0, and 3-device charging.',59.00,79.00,'Brand New',50,4.7,76,130,ARRAY['https://images.pexels.com/photos/4072683/pexels-photo-4072683.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'],false,true,true,true,'18 Month Anker Warranty','Free delivery in 2-3 business days'),
('Apple AirPods Pro 2','apple-airpods-pro-2','Apple',(SELECT id FROM cat WHERE slug='gadgets'),'Adaptive Audio, Active Noise Cancellation.','AirPods Pro 2 with H2 chip, 2x more noise cancellation, Adaptive Audio, and USB-C charging case.',249.00,279.00,'Brand New',45,4.8,134,280,ARRAY['https://images.pexels.com/photos/3921817/pexels-photo-3921817.jpeg?auto=compress&cs=tinysrgb&h=650&w=940','https://images.pexels.com/photos/33797659/pexels-photo-33797659.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'],true,false,true,true,'1 Year Apple Warranty','Free delivery in 2-3 business days'),
('Samsung Galaxy Buds 3','samsung-galaxy-buds-3','Samsung',(SELECT id FROM cat WHERE slug='gadgets'),'Premium wireless audio with ANC.','Galaxy Buds 3 with adaptive noise cancellation, 24-hour battery, and ergonomic design.',169.00,199.00,'Brand New',38,4.5,62,110,ARRAY['https://images.pexels.com/photos/33797659/pexels-photo-33797659.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'],false,true,true,false,'1 Year Samsung Warranty','Free delivery in 2-3 business days'),
('Wireless Charging Pad','wireless-charging-pad','Anker',(SELECT id FROM cat WHERE slug='gadgets'),'15W fast wireless charging.','Anker 15W wireless charging pad with Qi certification and foreign object detection.',29.00,39.00,'Brand New',60,4.4,42,85,ARRAY['https://images.pexels.com/photos/32583519/pexels-photo-32583519.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'],false,false,false,false,'18 Month Anker Warranty','Free delivery in 2-3 business days'),
('Toyota Camry 2022 (Pre-owned)','toyota-camry-2022-preowned','Toyota',(SELECT id FROM cat WHERE slug='cars'),'Certified pre-owned sedan, full service history.','Professionally inspected Toyota Camry 2022 with 25,000km, full service history, and 2.5L engine.',24500.00,28000.00,'Excellent',1,4.7,12,1,ARRAY['https://images.pexels.com/photos/15264151/pexels-photo-15264151.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'],true,false,true,false,'1 Year Declutter Warranty','Nationwide delivery available'),
('Mercedes-Benz C300 2021 (Pre-owned)','mercedes-c300-2021-preowned','Mercedes-Benz',(SELECT id FROM cat WHERE slug='cars'),'Certified pre-owned luxury sedan.','Professionally inspected Mercedes C300 with 30,000km, AMG line package, and panoramic roof.',32000.00,38000.00,'Very Good',1,4.6,8,1,ARRAY['https://images.pexels.com/photos/16180445/pexels-photo-16180445.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'],false,false,false,false,'6 Month Declutter Warranty','Nationwide delivery available'),
('Kawasaki Ninja ZX-10R','kawasaki-ninja-zx-10r','Kawasaki',(SELECT id FROM cat WHERE slug='motorcycles'),'Track-bred superbike for the street.','Kawasaki Ninja ZX-10R with 998cc inline-four, 200hp, and race-derived electronics.',18500.00,19900.00,'Brand New',2,4.8,15,3,ARRAY['https://images.pexels.com/photos/26551186/pexels-photo-26551186.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'],true,false,true,false,'2 Year Kawasaki Warranty','Pickup or nationwide delivery'),
('Honda CBR500R (Pre-owned)','honda-cbr500r-preowned','Honda',(SELECT id FROM cat WHERE slug='motorcycles'),'Certified pre-owned sport bike.','Professionally inspected Honda CBR500R with 12,000km, 471cc parallel-twin, and full service.',5500.00,7200.00,'Very Good',3,4.5,9,5,ARRAY['https://images.pexels.com/photos/33203538/pexels-photo-33203538.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'],false,false,false,false,'3 Month Declutter Warranty','Pickup or nationwide delivery'),
('USB-C Fast Charger 65W','usb-c-fast-charger-65w','Anker',(SELECT id FROM cat WHERE slug='accessories'),'GaN II technology, compact power.','Anker 65W USB-C charger with GaN II tech, PowerIQ 3.0, and dual-port charging.',39.00,49.00,'Brand New',80,4.6,54,92,ARRAY['https://images.pexels.com/photos/4195332/pexels-photo-4195332.jpeg?auto=compress&cs=tinysrgb&h=650&w=940','https://images.pexels.com/photos/4387770/pexels-photo-4387770.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'],false,false,true,true,'18 Month Anker Warranty','Free delivery in 2-3 business days'),
('Braided USB-C Cable 2m','braided-usb-c-cable-2m','Anker',(SELECT id FROM cat WHERE slug='accessories'),'Durable, fast, and tangle-free.','Anker nylon-braided USB-C to USB-C cable, 100W PD support, 2-meter length.',19.00,25.00,'Brand New',100,4.5,38,65,ARRAY['https://images.pexels.com/photos/4072683/pexels-photo-4072683.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'],false,false,false,false,'18 Month Anker Warranty','Free delivery in 2-3 business days')
) AS t(name, slug, brand, category_id, short_description, description, price, compare_at_price, condition, stock, rating, review_count, sales_count, images, is_featured, is_flash_deal, is_new_arrival, is_best_seller, warranty, delivery_info)
ON CONFLICT (slug) DO NOTHING;

-- Condition reports
INSERT INTO public.condition_reports (product_id, battery_health, cosmetic_condition, inspection_report, accessories_included, warranty_period)
SELECT p.id, '92% battery health', 'Minor scratches on the aluminum frame, screen is pristine', 'Full diagnostic passed: battery, camera, display, speakers, charging port, Face ID, and water-resistance seals all verified. No repair history.', ARRAY['Original box','USB-C cable','Documentation'], '6 months' FROM public.products p WHERE p.slug = 'iphone-13-128gb-preowned' ON CONFLICT (product_id) DO NOTHING;
INSERT INTO public.condition_reports (product_id, battery_health, cosmetic_condition, inspection_report, accessories_included, warranty_period)
SELECT p.id, '96% battery health', 'No visible scratches or dents, like-new condition', 'Full diagnostic passed: battery, keyboard, trackpad, display, ports, Wi-Fi, and Bluetooth all verified. Cycle count: 42.', ARRAY['Original box','30W USB-C power adapter','USB-C cable'], '6 months' FROM public.products p WHERE p.slug = 'macbook-air-m2-preowned' ON CONFLICT (product_id) DO NOTHING;
INSERT INTO public.condition_reports (product_id, battery_health, cosmetic_condition, inspection_report, accessories_included, warranty_period)
SELECT p.id, '88% battery health', 'Light wear on back glass, screen excellent', 'Full diagnostic passed: battery, touchscreen, haptics, sensors, and water-resistance verified.', ARRAY['USB-C cable'], '3 months' FROM public.products p WHERE p.slug = 'apple-watch-se-preowned' ON CONFLICT (product_id) DO NOTHING;
INSERT INTO public.condition_reports (product_id, battery_health, cosmetic_condition, inspection_report, accessories_included, warranty_period)
SELECT p.id, 'N/A', 'Cosmetically clean, minor scuff on side panel', 'Full service: refrigerant topped up, compressor tested, thermostat calibrated, condenser cleaned. Cooling performance verified.', ARRAY['Remote control'], '3 months' FROM public.products p WHERE p.slug = 'hisense-1hp-split-ac-preowned' ON CONFLICT (product_id) DO NOTHING;
INSERT INTO public.condition_reports (product_id, battery_health, cosmetic_condition, inspection_report, accessories_included, warranty_period)
SELECT p.id, 'N/A', 'Exterior clean, shelves intact', 'Full service: compressor tested, thermostat calibrated, door seals replaced, interior deep-cleaned and sanitized.', ARRAY['User manual'], '3 months' FROM public.products p WHERE p.slug = 'lg-top-freezer-fridge-preowned' ON CONFLICT (product_id) DO NOTHING;
INSERT INTO public.condition_reports (product_id, battery_health, cosmetic_condition, inspection_report, accessories_included, warranty_period)
SELECT p.id, 'N/A', 'Minor scratches on top surface, drum pristine', 'Full diagnostic: motor, pump, drum, control board, and all cycles tested. Inverter verified.', ARRAY['Water hose','User manual'], '3 months' FROM public.products p WHERE p.slug = 'samsung-top-load-washer-12kg-preowned' ON CONFLICT (product_id) DO NOTHING;
INSERT INTO public.condition_reports (product_id, battery_health, cosmetic_condition, inspection_report, accessories_included, warranty_period)
SELECT p.id, 'N/A', 'Minor cosmetic wear on chassis, all ports functional', 'Full diagnostic: disc drive, HDMI, controllers, cooling fan, and all ports tested. Firmware updated.', ARRAY['One DualSense controller','HDMI cable','Power cable'], '6 months' FROM public.products p WHERE p.slug = 'playstation-5-preowned' ON CONFLICT (product_id) DO NOTHING;
INSERT INTO public.condition_reports (product_id, battery_health, cosmetic_condition, inspection_report, accessories_included, warranty_period)
SELECT p.id, 'N/A', 'Body like-new, no scratches on sensor', 'Full diagnostic: sensor, shutter (count: 8,400), autofocus, IBIS, and all ports tested. Firmware updated.', ARRAY['Original box','Battery','Charger','Strap'], '6 months' FROM public.products p WHERE p.slug = 'sony-alpha-a7-iv-preowned' ON CONFLICT (product_id) DO NOTHING;
INSERT INTO public.condition_reports (product_id, battery_health, cosmetic_condition, inspection_report, accessories_included, warranty_period)
SELECT p.id, 'N/A', 'Cabinet has minor scuffs, drivers perfect', 'Full diagnostic: drivers, tweeter, amplifier, Wi-Fi, and voice control tested. Sound profile calibrated.', ARRAY['Power cable'], '3 months' FROM public.products p WHERE p.slug = 'sonos-one-preowned' ON CONFLICT (product_id) DO NOTHING;
INSERT INTO public.condition_reports (product_id, battery_health, cosmetic_condition, inspection_report, accessories_included, warranty_period)
SELECT p.id, 'N/A', 'Container like-new, blades sharp', 'Full diagnostic: motor, blades, container seal, and all programs tested.', ARRAY['Tamper','Recipe book'], '6 months' FROM public.products p WHERE p.slug = 'vitamix-a3500-preowned' ON CONFLICT (product_id) DO NOTHING;
INSERT INTO public.condition_reports (product_id, battery_health, cosmetic_condition, inspection_report, accessories_included, warranty_period)
SELECT p.id, 'N/A', 'Exterior excellent, interior detailed', 'Full inspection: engine, transmission, brakes, tires (60% tread), electrical systems, and AC all verified. Service history available.', ARRAY['2 keys','Service records','Floor mats'], '1 year' FROM public.products p WHERE p.slug = 'toyota-camry-2022-preowned' ON CONFLICT (product_id) DO NOTHING;
INSERT INTO public.condition_reports (product_id, battery_health, cosmetic_condition, inspection_report, accessories_included, warranty_period)
SELECT p.id, 'N/A', 'Minor wear on driver seat, exterior pristine', 'Full inspection: engine, transmission, brakes, tires (55% tread), electrical, and panoramic roof verified.', ARRAY['2 keys','Service records'], '6 months' FROM public.products p WHERE p.slug = 'mercedes-c300-2021-preowned' ON CONFLICT (product_id) DO NOTHING;
INSERT INTO public.condition_reports (product_id, battery_health, cosmetic_condition, inspection_report, accessories_included, warranty_period)
SELECT p.id, 'N/A', 'Fair condition: minor scratches on fairings', 'Full inspection: engine, chain, brakes, tires (50% tread), and electrical systems verified.', ARRAY['1 key','Service records'], '3 months' FROM public.products p WHERE p.slug = 'honda-cbr500r-preowned' ON CONFLICT (product_id) DO NOTHING;
INSERT INTO public.condition_reports (product_id, battery_health, cosmetic_condition, inspection_report, accessories_included, warranty_period)
SELECT p.id, 'N/A', 'Screen excellent, minor wear on edges', 'Full diagnostic: display, Touch ID, battery (cycle count: 120), ports, and Wi-Fi verified.', ARRAY['Original box','USB-C cable'], '6 months' FROM public.products p WHERE p.slug = 'ipad-air-preowned' ON CONFLICT (product_id) DO NOTHING;

-- Product specs
INSERT INTO public.product_specs (product_id, spec_key, spec_value, sort_order)
SELECT p.id, k, v, s FROM public.products p
JOIN (VALUES
  ('iphone-15-pro-max-256gb','Display','6.7" Super Retina XDR OLED',1),('iphone-15-pro-max-256gb','Chip','A17 Pro',2),('iphone-15-pro-max-256gb','Storage','256GB',3),('iphone-15-pro-max-256gb','Camera','48MP Main + 12MP Ultra Wide + 12MP Telephoto',4),('iphone-15-pro-max-256gb','Battery','Up to 29 hours video playback',5),('iphone-15-pro-max-256gb','Connectivity','5G, Wi-Fi 6E, Bluetooth 5.3, USB-C',6),('iphone-15-pro-max-256gb','Weight','221g',7),
  ('macbook-pro-14-m3-pro','Display','14.2" Liquid Retina XDR',1),('macbook-pro-14-m3-pro','Chip','M3 Pro',2),('macbook-pro-14-m3-pro','Memory','18GB unified',3),('macbook-pro-14-m3-pro','Storage','512GB SSD',4),('macbook-pro-14-m3-pro','Battery','Up to 18 hours',5),('macbook-pro-14-m3-pro','Ports','3x Thunderbolt 4, HDMI, SDXC, MagSafe 3',6),('macbook-pro-14-m3-pro','Weight','1.61kg',7),
  ('samsung-55-qled-4k-tv','Display','55" QLED 4K UHD',1),('samsung-55-qled-4k-tv','Resolution','3840 x 2160',2),('samsung-55-qled-4k-tv','HDR','Quantum HDR+',3),('samsung-55-qled-4k-tv','Smart OS','Tizen',4),('samsung-55-qled-4k-tv','HDMI','3 ports',5),
  ('playstation-5-slim','CPU','AMD Zen 2, 8 cores',1),('playstation-5-slim','GPU','AMD RDNA 2, 10.28 TFLOPs',2),('playstation-5-slim','Storage','1TB SSD',3),('playstation-5-slim','Resolution','Up to 4K 120fps',4),('playstation-5-slim','Controller','DualSense',5)
) AS x(slug, k, v, s) ON p.slug = x.slug
ON CONFLICT DO NOTHING;

-- Banners
INSERT INTO public.banners (title, subtitle, image_url, cta_text, cta_link, sort_order) VALUES
('Certified Pre-Owned. Professionally Inspected.','Every refurbished product is tested, graded, and backed by warranty. Save up to 40% without the risk.','https://images.pexels.com/photos/13577780/pexels-photo-13577780.jpeg?auto=compress&cs=tinysrgb&h=650&w=940','Shop Pre-Owned','/products?condition=pre-owned',1),
('New Arrivals Are Here.','The latest phones, laptops, and gadgets from the brands you love.','https://images.pexels.com/photos/9203155/pexels-photo-9203155.jpeg?auto=compress&cs=tinysrgb&h=650&w=940','Explore New Arrivals','/products?sort=newest',2),
('Flash Deals — Up to 30% Off.','Limited-time savings on premium electronics and appliances. While stocks last.','https://images.pexels.com/photos/29022333/pexels-photo-29022333.jpeg?auto=compress&cs=tinysrgb&h=650&w=940','Shop Flash Deals','/products?filter=flash-deals',3)
ON CONFLICT DO NOTHING;

-- Coupons
INSERT INTO public.coupons (code, type, value, min_order, max_discount, usage_limit, expires_at) VALUES
('WELCOME10','percent',10.00,0.00,200.00,1000,'2026-12-31 23:59:59+00'),
('FLASH20','percent',20.00,500.00,500.00,500,'2026-12-31 23:59:59+00'),
('SAVE5000','fixed',5000.00,50000.00,NULL,100,'2026-12-31 23:59:59+00')
ON CONFLICT (code) DO NOTHING;

-- Settings
INSERT INTO public.settings (key, value) VALUES
('site_name','Declutter'),
('whatsapp_number','+2348000000000'),
('free_shipping_threshold','50000'),
('flat_shipping_rate','2500'),
('currency','NGN'),
('currency_symbol','₦'),
('contact_email','support@declutter.com'),
('contact_phone','+234 800 000 0000'),
('address','12 Adeola Odeon Street, Victoria Island, Lagos, Nigeria')
ON CONFLICT (key) DO NOTHING;
